buckets: 
  - hao-us-east-1
  - hao-ap-southeast-2
  - hao-ap-northeast-1
  - hao-eu-west-2
  - hao-sa-east-1
  - hao-ca-central-1
  - hao-us-west-1
regions:
  - us-east-1
  - ap-southeast-2
  - ap-northeast-1
  - eu-west-2
  - sa-east-1
  - ca-central-1
  - us-west-1
file_size_kb: 51200
username: hl7gr

multi_local_clients: True 
num_local_clients: 5

start_time: "13:06:00"
gap_sec: 180
between_req_sec: 2
between_bucket_sec: 180
total_benchmarking_duration_sec: 86400








