buckets: 
  - hao-us-east-1
  - hao-ap-southeast-2
  - hao-ap-northeast-1
  - hao-eu-west-2
  - hao-sa-east-1
  - hao-ca-central-1
  - hao-us-west-1
regions:
  - us-east-1
  - ap-southeast-2
  - ap-northeast-1
  - eu-west-2
  - sa-east-1
  - ca-central-1
  - us-west-1
file_size_kb: 1024
node_ips:
  - 127.0.0.1
  - 127.0.0.2
req_times:
  - "16:45:00"
  - "16:45:10"
  - "16:45:20"
  - "16:45:30"
  - "16:45:40"
  - "16:45:50"
  - "16:45:00"

